//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Oxygene Version: 5.0.30.954
//     Runtime Version: 4.0.30319.239
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace RemObjects.Calendar;

interface

uses
  System,
  RemObjects.SDK,
  RemObjects.SDK.Types,
  RemObjects.SDK.Server,
  RemObjects.DataAbstract.Server;
  
type
  [RemObjects.SDK.Server.Invoker]
  [System.Reflection.ObfuscationAttribute(Exclude := true)]
  DataService_Invoker = public class(RemObjects.DataAbstract.Server.DataAbstractService_Invoker)
  public 
    constructor;
  end;
  
  [RemObjects.SDK.Activator]
  [System.Reflection.ObfuscationAttribute(Exclude := true, ApplyToMembers := false)]
  DataService_Activator = public class(RemObjects.DataAbstract.Server.DataAbstractService_Activator)
  public 
    constructor;
    method CreateInstance: RemObjects.SDK.IROService; override;
  end;
  
implementation

{ DataService_Invoker }

constructor DataService_Invoker;
begin
  inherited constructor();
end;

{ DataService_Activator }

constructor DataService_Activator;
begin
  inherited constructor();
end;

method DataService_Activator.CreateInstance: RemObjects.SDK.IROService;
begin
  exit(new DataService());
end;

end.
