//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Oxygene Version: 5.0.30.954
//     Runtime Version: 4.0.30319.239
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace RemObjects.Calendar;

interface

uses
  System,
  RemObjects.SDK,
  RemObjects.SDK.Types,
  System.Collections.Generic,
  RemObjects.DataAbstract.Server;
  
type
  IDataService = public interface(RemObjects.DataAbstract.Server.IDataAbstractService)
  end;
  
  DataService_Proxy = public partial class(RemObjects.DataAbstract.Server.DataAbstractService_Proxy, IDataService)
  protected 
    method __GetInterfaceName: System.String; override;
  public 
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
  end;
  
  CoDataService = public class
  public 
    class method &Create(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel): IDataService;
    class method &Create(aRemoteService: RemObjects.SDK.IRemoteService): IDataService;
  end;
  
  IDataService_Async = public interface(RemObjects.DataAbstract.Server.IDataAbstractService_Async)
  end;
  
  DataService_AsyncProxy = public partial class(RemObjects.DataAbstract.Server.DataAbstractService_AsyncProxy, IDataService_Async)
  protected 
    method __GetInterfaceName: System.String; override;
  public 
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
  end;
  
implementation

{ DataService_Proxy }

method DataService_Proxy.__GetInterfaceName: System.String;
begin
  exit('DataService');
end;

constructor DataService_Proxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
begin
  inherited constructor(aMessage, aClientChannel);
end;

constructor DataService_Proxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aMessage, aClientChannel, aOverrideInterfaceName);
end;

constructor DataService_Proxy(aRemoteService: RemObjects.SDK.IRemoteService);
begin
  inherited constructor(aRemoteService);
end;

constructor DataService_Proxy(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aRemoteService, aOverrideInterfaceName);
end;

{ CoDataService }

class method CoDataService.&Create(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel): IDataService;
begin
  exit(new DataService_Proxy(aMessage, aClientChannel));
end;

class method CoDataService.&Create(aRemoteService: RemObjects.SDK.IRemoteService): IDataService;
begin
  exit(new DataService_Proxy(aRemoteService));
end;

{ DataService_AsyncProxy }

method DataService_AsyncProxy.__GetInterfaceName: System.String;
begin
  exit('DataService');
end;

constructor DataService_AsyncProxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
begin
  inherited constructor(aMessage, aClientChannel);
end;

constructor DataService_AsyncProxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aMessage, aClientChannel, aOverrideInterfaceName);
end;

constructor DataService_AsyncProxy(aRemoteService: RemObjects.SDK.IRemoteService);
begin
  inherited constructor(aRemoteService);
end;

constructor DataService_AsyncProxy(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aRemoteService, aOverrideInterfaceName);
end;

end.
